runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /apple-touch-icon\.png
  static_files: apple-touch-icon.png
  upload: apple-touch-icon\.png

- url: /favicon-32x32\.png
  static_files: favicon-32x32.png
  upload: favicon-32x32\.png

- url: /favicon-16x16\.png
  static_files: favicon-16x16.png
  upload: favicon-16x16\.png

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: exp-traq.app
  login: admin
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
